language: c
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # needed for gfortran-6
    packages:
      - gfortran-6
      - binutils
      - lcov
      - doxygen

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build/doc
  on:
    branch: master

sudo: false

cache:
  apt: true

install:
  - mkdir build && cd build
  - export FC=gfortran-6
  - cmake .. -DCMAKE_Fortran_FLAGS='--coverage' -DWITH_DOXYGEN=ON
  - make VERBOSE=1
  - make test
  - make doc
  - lcov -c -d . -o fht_coverage.info
  - genhtml fht_coverage.info --output-directory doc/coverage

script:
  - ctest -V
